const PREFIX = "student";

export const CREATE_STUDENT = `${PREFIX}/CREATE_STUDENT`;
export const GET_STUDENT_DETAIL = `${PREFIX}/GET_STUDENT_DETAIL`;
export const UPDATE_STUDENT = `${PREFIX}/UPDATE_STUDENT`;
export const DELETE_STUDENT = `${PREFIX}/DELETE_STUDENT`;
export const SEARCH_STUDENT = `${PREFIX}/SEARCH_STUDENT`;
